/** Тексты кабинета держим рядом, чтобы терминология не расходилась между экранами. */
export const texts = {
    app: { back: 'Назад' },
    auth: {
        loading: 'Входим…',
        openInMax: 'Откройте кабинет из бота в MAX',
        openInMaxHint: 'Мини-приложение работает внутри MAX. Нажмите «Кабинет» в боте.',
        demoTitle: 'Проверка в браузере',
        demoHint: 'demo_dispatcher — очередь заявок. demo_resident — свои заявки.',
        login: 'Логин',
        password: 'Пароль',
        showPassword: 'Показать пароль',
        hidePassword: 'Скрыть пароль',
        submit: 'Войти',
        logout: 'Выйти',
    },
    home: {
        title: 'Кабинет',
        dispatcherTitle: 'Кабинет',
        dispatcherRole: 'Диспетчер',
        dispatcherMenu: 'Заявки',
        allRequests: 'Все заявки',
        allRequestsHint: 'Все сразу, можно искать',
        newRequestsHint: 'Ещё никто не взял',
        inProgressHint: 'Уже делают',
        overdueHint: 'Срок вышел — откройте сначала эти',
        closedHint: 'Уже сделали или передали дальше',
        organization: 'Организация',
        organizationHint: 'Контакты, дома, исполнители',
        residentTitle: 'Кабинет',
        residentRole: 'Житель',
        myRequests: 'Мои заявки',
        myRequestsHint: 'Что сейчас делают',
        pastRequests: 'Прошлые заявки',
        pastRequestsHint: 'Уже закрытые заявки',
        house: 'Дом и контакты',
        houseHint: 'Адрес, организация и телефоны',
        createRequest: 'Сообщить о проблеме',
        createRequestHint: 'Новая заявка в организацию',
    },
    queue: {
        title: 'Заявки',
        tabs: { new: 'Новые', in_progress: 'В работе', overdue: 'Просрочено', closed: 'Выполнено' },
        search: 'Найти: номер, квартира или улица',
        empty: {
            new: 'Новых заявок нет.',
            in_progress: 'Сейчас ничего не делают.',
            overdue: 'Просроченных заявок нет.',
            closed: 'Закрытых заявок нет.',
        },
        retry: 'Повторить',
        loadMore: 'Показать ещё заявки',
        neighbors: (n: number) => {
            if (n === 1) return 'Ещё 1 сосед с той же проблемой';
            if (n < 5) return `Ещё ${n} соседа с той же проблемой`;
            return `Ещё ${n} соседей с той же проблемой`;
        },
        filters: 'Какие заявки показать',
    },
    resident: {
        title: 'Мои заявки',
        current: 'Текущие',
        past: 'Прошлые',
        empty: 'Открытых заявок нет.',
        emptyPast: 'Закрытых заявок пока нет.',
        house: 'Дом',
        address: 'Адрес',
        noHouse: 'Дом ещё не привязан.',
        entrance: 'Подъезд',
        flat: 'Квартира',
        create: 'Сообщить о проблеме',
        category: 'Что случилось',
        description: 'Опишите проблему',
        submit: 'Отправить заявку',
        emergency: 'Это авария. Позвоните в аварийную службу — заявку по ней не создаём.',
        created: 'Заявка отправлена',
    },
    organization: {
        title: 'Организация',
        name: 'Название',
        contacts: 'Контакты',
        phoneAds: 'Аварийная служба',
        phoneDispatch: 'Диспетчерская',
        email: 'Почта',
        hours: 'Часы приёма',
        address: 'Адрес приёма',
        contracts: 'Прямые договоры с РСО',
        contractsHint: 'Если договор прямой, по этой услуге отвечает поставщик.',
        houses: 'Дома',
        houseChat: 'Чат дома привязан',
        houseNoChat: 'Чат дома не привязан',
        joinInChat: 'Предлагать присоединиться',
        joinInChatHint: 'Если в чате пишут о той же проблеме, бот предложит присоединиться к заявке.',
        openHouse: 'Ссылка для жителя',
        houseLinkCopied: 'Ссылка скопирована',
        entrances: 'Подъездов',
        save: 'Сохранить',
        saved: 'Сохранено',
        cancel: 'Отмена',
        executors: 'Исполнители',
        executorsEmpty: 'Исполнителей пока нет.',
        addExecutor: 'Добавить исполнителя',
        saveExecutor: 'Сохранить исполнителя',
        archiveExecutor: 'Убрать',
        archiveConfirm: 'Убрать этого исполнителя?',
        archiveYes: 'Да, убрать',
        executorAdded: 'Исполнитель добавлен',
        executorSaved: 'Исполнитель сохранён',
        executorRemoved: 'Исполнитель убран',
        executorName: 'Имя',
        executorNameRequired: 'Укажите имя',
        executorPhone: 'Телефон',
        phonePrefix: '+7',
        phoneError: 'Введите 10 цифр, без +7',
        executorSpecialty: 'Специальность',
        types: { uk: 'УК', tsj: 'ТСЖ', jsk: 'ЖСК' },
        contractsLabels: {
            cold_water: 'Холодная вода',
            hot_water: 'Горячая вода',
            heat: 'Тепло',
            power: 'Электричество',
            tko: 'ТКО',
        },
    },
    request: {
        title: (id: number) => `Заявка № ${id}`,
        openRow: 'Открыть заявку',
        where: 'Где это',
        what: 'Что случилось',
        invalidTitle: 'Заявка',
        execution: 'Кто и когда сделает',
        responsible: 'Кто отвечает',
        deadline: 'К какому сроку',
        replyDeadline: 'До какого дня ответить по закону',
        basis: 'Основание',
        unsure: 'Это пока неточно. Если нужно — передайте другой службе.',
        history: 'Что уже было',
        executor: 'Мастер',
        noExecutor: 'Мастера пока нет',
        assign: 'Кто пойдёт делать',
        assignEmpty: 'Сначала добавьте мастеров в организации.',
        assigned: 'Назначен',
        commentPlaceholder: 'Напишите, что сделали или что мешает',
        actions: { redirect: 'Передать другой службе', comment: 'Написать комментарий' },
        notFound: 'Эту заявку не нашли. Нажмите Назад.',
        awaitingResident: 'Сделали. Ждём, что скажет житель',
        returnedBadge: 'Житель сказал: ещё не готово',
        joined: (n: number) => `Соседей с той же проблемой: ${n}`,
        neighbors: 'Соседи',
        redirected: 'Кому передали',
        photos: 'Фотографии',
        residentPhoto: 'Фото жителя',
        closingPhoto: 'Фото после работы',
        historyEmpty: 'Пока ничего не происходило',
        actionTitle: 'Что сделать',
        resolvedTitle: 'Проблему решили?',
        finishTitle: 'Работа закончена?',
        finishComment: 'Напишите, что сделали',
        addPhoto: 'Добавить фото',
        selectedPhotos: (n: number) => `Фото: ${n} из 5`,
        removePhoto: (name: string) => `Убрать фото «${name}»`,
        photoLimit: 'Можно не больше пяти фото.',
        finishSubmit: 'Да, работа сделана',
        redirectName: 'Какой службе передать',
        redirectPhone: 'Телефон, если есть',
        redirectNote: 'Что сказать жителю',
        redirectSubmit: 'Передать заявку',
        returnComment: 'Напишите, что ещё не так',
        confirmYes: 'Да, всё хорошо',
        confirmNo: 'Нет, ещё не готово',
        events: {
            created: 'Заявка принята',
            assigned: 'Назначен исполнитель',
            statusChanged: 'Статус изменён',
            redirected: 'Заявка переадресована',
            returned: 'Житель вернул заявку в работу',
            confirmed: 'Решение подтверждено',
            comment: 'Комментарий',
            photoAdded: 'Добавлена фотография',
            participantJoined: 'Присоединился сосед',
            notification: 'Жителю отправлено уведомление',
            reminder: 'Отправлено напоминание',
        },
    },
    errors: {
        network: 'Нет связи. Проверьте интернет и повторите.',
        forbidden: 'Нет доступа к этому разделу.',
        generic: 'Что-то пошло не так. Попробуйте ещё раз.',
    },
} as const;
