/** Тексты кабинета держим рядом, чтобы терминология не расходилась между экранами. */
export const texts = {
    app: { back: 'Назад' },
    auth: {
        loading: 'Входим…',
        openInMax: 'Откройте кабинет из бота в MAX',
        openInMaxHint: 'Мини-приложение работает внутри MAX. Нажмите «Кабинет» в боте.',
        demoTitle: 'Вход для проверки',
        demoHint:
            'Логины demo_dispatcher (кабинет) и demo_resident (мои заявки). Пароли — значения DEMO_DISPATCHER_PASSWORD и DEMO_RESIDENT_PASSWORD из .env. В MAX вход происходит автоматически.',
        login: 'Логин',
        password: 'Пароль',
        submit: 'Войти',
        logout: 'Выйти',
    },
    home: {
        title: 'Главная',
        dispatcherTitle: 'Кабинет диспетчера',
        dispatcherRole: 'Диспетчер',
        dispatcherDescription: 'Выберите раздел очереди. Сначала проверьте новые и просроченные заявки.',
        dispatcherMenu: 'Разделы заявок',
        allRequests: 'Все заявки',
        allRequestsHint: 'Поиск и полный список заявок',
        newRequestsHint: 'Заявки, которые ещё не взяли в работу',
        inProgressHint: 'Заявки, которые уже обрабатываются',
        overdueHint: 'Требуют внимания в первую очередь',
        closedHint: 'Выполненные и переадресованные заявки',
        residentTitle: 'Кабинет жителя',
        residentRole: 'Житель',
        residentDescription: 'Сообщайте о проблемах и следите, как выполняются ваши заявки.',
        myRequests: 'Мои заявки',
        myRequestsHint: 'Статусы, сроки и ответы исполнителей',
        reportProblem: 'Сообщить о проблеме',
        reportProblemHint: 'Вернуться в бот и создать новую заявку',
        browserReportHint:
            'Чтобы создать заявку, откройте чат с ботом в MAX и нажмите «Сообщить о проблеме».',
        howItWorks: 'Как это работает',
        steps: [
            'Опишите проблему в боте MAX.',
            'Следите за статусом в разделе «Мои заявки».',
            'Подтвердите, когда проблема будет решена.',
        ],
    },
    queue: {
        title: 'Заявки',
        tabs: { new: 'Новые', in_progress: 'В работе', overdue: 'Просрочено', closed: 'Закрытые' },
        search: 'Номер, квартира или адрес',
        empty: {
            new: 'Новых заявок нет. Жители попадают в бот по QR в подъезде или из закрепа в чате дома.',
            in_progress: 'В работе ничего нет.',
            overdue: 'Просроченных заявок нет.',
            closed: 'Закрытых заявок пока нет.',
        },
        retry: 'Повторить',
        loadMore: 'Загрузить ещё',
        neighbors: (n: number) => `${n} сосед${n === 1 ? '' : n < 5 ? 'а' : 'ей'}`,
    },
    resident: {
        title: 'Мои заявки',
        empty: 'У вас пока нет заявок. Нажмите «Сообщить о проблеме» в боте.',
    },
    request: {
        title: (id: number) => `Заявка № ${id}`,
        invalidTitle: 'Заявка',
        execution: 'Исполнение',
        responsible: 'Кто отвечает',
        deadline: 'Срок',
        replyDeadline: 'Срок ответа по закону',
        basis: 'Основание',
        unsure: 'Ответственный определён предварительно — при необходимости переадресуйте',
        history: 'История',
        executor: 'Исполнитель',
        noExecutor: 'не назначен',
        commentPlaceholder: 'Что сделано или что мешает',
        actions: { redirect: 'Переадресовать', comment: 'Добавить комментарий' },
        notFound: 'Заявка не найдена или недоступна',
        awaitingResident: 'Ждём подтверждения жителя',
        returnedBadge: 'Житель вернул в работу',
        joined: (n: number) => `Соседей присоединилось: ${n}`,
        redirected: 'Переадресовано',
        photos: 'Фотографии',
        residentPhoto: 'Фото жителя',
        closingPhoto: 'Фото результата',
        historyEmpty: 'История пока пуста',
        actionTitle: 'Действия по заявке',
        resolvedTitle: 'Проблема решена?',
        finishTitle: 'Завершить работу',
        finishComment: 'Что сделано',
        addPhoto: 'Добавить фото',
        selectedPhotos: (n: number) => `Выбрано фото: ${n} из 5`,
        removePhoto: (name: string) => `Убрать фото «${name}»`,
        photoLimit: 'Можно прикрепить не больше пяти фотографий.',
        finishSubmit: 'Отметить выполненной',
        redirectName: 'Организация или служба',
        redirectPhone: 'Телефон (необязательно)',
        redirectNote: 'Комментарий для жителя (необязательно)',
        redirectSubmit: 'Подтвердить переадресацию',
        returnComment: 'Комментарий, если проблема осталась',
        confirmYes: 'Да, решено',
        confirmNo: 'Нет',
        events: {
            created: 'Заявка принята',
            assigned: 'Назначен исполнитель',
            statusChanged: 'Статус изменён',
            redirected: 'Заявка переадресована',
            returned: 'Житель вернул заявку в работу',
            confirmed: 'Решение подтверждено',
            comment: 'Комментарий',
            photoAdded: 'Добавлена фотография',
            participantJoined: 'Присоединился сосед',
            notification: 'Жителю отправлено уведомление',
            reminder: 'Отправлено напоминание',
        },
    },
    errors: {
        network: 'Нет связи. Проверьте интернет и повторите.',
        forbidden: 'Нет доступа к этому разделу.',
        generic: 'Что-то пошло не так. Попробуйте ещё раз.',
    },
} as const;
