/** Подписи кабинета в одном месте, чтобы на экранах звучало одинаково. */
export const texts = {
    app: { back: 'Назад', loading: 'Загрузка…', copied: 'Скопировано', clear: 'Очистить' },
    auth: {
        loading: 'Входим…',
        title: 'Вход в кабинет',
        openInMax: 'Откройте кабинет из бота в MAX',
        openInMaxHint: 'Мини-приложение работает внутри MAX. Нажмите «Кабинет» в боте.',
        demoTitle: 'Проверка в браузере',
        demoHint: 'demo_dispatcher — очередь заявок. demo_resident — свои заявки.',
        login: 'Логин',
        password: 'Пароль',
        showPassword: 'Показать пароль',
        hidePassword: 'Скрыть пароль',
        submit: 'Войти',
        logout: 'Выйти',
        badCredentials: 'Неверный логин или пароль',
        unavailable: 'Вход по паролю сейчас недоступен',
    },
    home: {
        title: 'Кабинет',
        dispatcherTitle: 'Кабинет',
        dispatcherRole: 'Диспетчер',
        dispatcherMenu: 'Заявки',
        allRequests: 'Все заявки',
        allRequestsHint: 'Все сразу, можно искать',
        newRequestsHint: 'Ещё никто не взял',
        inProgressHint: 'Уже делают',
        overdueHint: 'Срок вышел — откройте сначала эти',
        closedHint: 'Уже сделали или передали дальше',
        organization: 'Организация',
        organizationHint: 'Контакты, договоры, дома, журнал',
        residentTitle: 'Кабинет',
        residentRole: 'Житель',
        myRequests: 'Мои заявки',
        myRequestsHint: 'Что сейчас делают',
        pastRequests: 'Прошлые заявки',
        pastRequestsHint: 'Уже закрытые заявки',
        house: 'Вы',
        houseHint: 'Кто вы и где живёте',
        closeSheet: 'Закрыть',
        createRequest: 'Сообщить о проблеме',
        createRequestHint: 'Написать боту',
        createRequestNotice: 'О проблеме пишут в чате дома',
    },
    queue: {
        title: 'Заявки',
        tabs: { new: 'Новые', in_progress: 'В работе', overdue: 'Просрочено', closed: 'Закрытые' },
        search: 'Найти: номер, квартира или улица',
        empty: {
            new: 'Новых заявок нет.',
            in_progress: 'Сейчас ничего не делают.',
            overdue: 'Просроченных заявок нет.',
            closed: 'Закрытых заявок нет.',
        },
        retry: 'Повторить',
        loadMore: 'Показать ещё заявки',
        neighbors: (n: number) => {
            if (n === 1) return 'Ещё 1 сосед с той же проблемой';
            if (n < 5) return `Ещё ${n} соседа с той же проблемой`;
            return `Ещё ${n} соседей с той же проблемой`;
        },
        filters: 'Какие заявки показать',
    },
    resident: {
        title: 'Мои заявки',
        current: 'Текущие',
        past: 'Прошлые',
        empty: 'Открытых заявок нет.',
        emptyPast: 'Закрытых заявок пока нет.',
        house: 'Дом',
        address: 'Адрес',
        noHouse: 'Дом ещё не привязан.',
        entrance: 'Подъезд',
        flat: 'Квартира',
        create: {
            emergencyTitle: 'Это авария?',
            emergencyHint:
                'Прорыв трубы, запах газа, короткое замыкание, застрявший лифт — звонок в аварийную службу, не заявка.',
            emergencyYes: 'Да, авария',
            emergencyNo: 'Нет, не авария',
            callAds: 'Позвонить в аварийную службу',
            noAds: 'Телефон аварийной службы не указан. Он на стенде в подъезде.',
            category: 'Что случилось',
            subcategory: 'Уточните',
            details: 'Подробнее',
            detailsHint: 'Фото не обязательно. Без фото напишите пару слов.',
            detailsPlaceholder: 'Коротко, что не так',
            detailsRequired: 'Напишите, что случилось, или добавьте фото.',
            address: 'Где это',
            sameAddress: 'Как в прошлый раз',
            preview: 'Проверьте заявку',
            send: 'Отправить',
            unsure: 'Не уверен, кто отвечает',
            next: 'Дальше',
        },
    },
    organization: {
        title: 'Организация',
        name: 'Название',
        contacts: 'Контакты',
        contactsHint: 'Название, телефоны и почта',
        contractsHintShort: 'Какие услуги закрывает РСО',
        housesHint: 'QR, чат и ссылка для жителей',
        housesEmpty: 'Домов пока нет.',
        executorsHint: 'Кто выезжает на заявки',
        contractorsHintShort: 'Кому сразу уходят заявки',
        phoneAds: 'Аварийная служба',
        phoneDispatch: 'Диспетчерская',
        email: 'Почта',
        emailError: 'Укажите правильную почту',
        nameRequired: 'Укажите название',
        hours: 'Часы приёма',
        address: 'Адрес приёма',
        contracts: 'Прямые договоры с РСО',
        contractsHint: 'Если договор прямой, по этой услуге отвечает поставщик.',
        houses: 'Дома',
        houseChat: 'Чат дома привязан',
        houseNoChat: 'Чат дома не привязан',
        joinInChat: 'Предлагать присоединиться',
        joinInChatHint: 'Если в чате пишут о той же проблеме, бот предложит присоединиться к заявке.',
        openHouse: 'Ссылка для жителя',
        houseLinkCopied: 'Ссылка скопирована',
        entrances: 'Подъездов',
        save: 'Сохранить',
        saved: 'Сохранено',
        cancel: 'Отмена',
        executors: 'Исполнители',
        executorsEmpty: 'Исполнителей пока нет.',
        addExecutor: 'Добавить исполнителя',
        saveExecutor: 'Сохранить исполнителя',
        archiveExecutor: 'Убрать',
        archiveConfirm: 'Убрать этого исполнителя?',
        archiveYes: 'Да, убрать',
        executorAdded: 'Исполнитель добавлен',
        executorSaved: 'Исполнитель сохранён',
        executorRemoved: 'Исполнитель убран',
        executorName: 'Имя',
        executorNameRequired: 'Укажите имя',
        executorPhone: 'Телефон',
        phonePrefix: '+7',
        phoneRequired: 'Укажите номер телефона',
        phoneError: 'Введите 10 цифр, без +7',
        executorSpecialty: 'Специальность',
        houseBind: 'Как привязать чат',
        houseBindCommand: (token: string) => `/дом ${token}`,
        houseBindHint: 'Напишите эту команду в чате дома. Привязать может сотрудник организации.',
        houseBindCopied: 'Команда скопирована',
        housePinned: 'Карточка закреплена в чате',
        houseNotPinned: 'Карточка не закреплена. Сделайте бота администратором чата.',
        qrDownload: 'Скачать QR',
        qrDownloaded: 'QR скачан',
        types: { uk: 'УК', tsj: 'ТСЖ', jsk: 'ЖСК' },
        contractsLabels: {
            cold_water: 'Холодная вода',
            hot_water: 'Горячая вода',
            heat: 'Тепло',
            power: 'Электричество',
            tko: 'ТКО',
        },
        contractors: 'Подрядчики',
        contractorsHint: 'Заявки этого типа сразу идут к ним — например, поломка лифта.',
        contractorsEmpty: 'Подрядчиков пока нет.',
        contractorName: 'Название',
        contractorNameRequired: 'Укажите название',
        contractorPhone: 'Телефон',
        contractorType: 'Какие заявки',
        addContractor: 'Добавить подрядчика',
        removeContractor: 'Убрать',
        removeContractorConfirm: 'Убрать этого подрядчика?',
        removeContractorYes: 'Да, убрать',
        contractorAdded: 'Подрядчик добавлен',
        contractorRemoved: 'Подрядчик убран',
        contractorTypes: { lift: 'Лифт', intercom: 'Домофон', tko: 'ТКО', other: 'Другое' },
        qr: 'QR для плаката',
        qrAlt: 'QR-код дома',
        qrWholeHouse: 'Весь дом',
        qrEntrance: 'Подъезд для плаката',
        qrOpen: 'Открыть QR',
    },
    journal: {
        title: 'Журнал заявок',
        hint: 'Принятые заявки, сроки и выгрузка',
        from: 'С даты',
        to: 'По дату',
        periodHint: 'Не длиннее года, по дате приёма.',
        periodInvalid: 'Дата «по» не раньше даты «с».',
        periodTooLong: 'Период журнала не длиннее года.',
        empty: 'За этот период заявок нет.',
        csv: 'Скачать CSV',
        csvDone: 'CSV скачивается в браузере',
        summary: {
            total: 'Принято',
            open: 'Открыто',
            overdue: 'Просрочено',
            closed: 'Закрыто',
            on_time: 'Вовремя',
            late: 'После срока',
            returned: 'Вернули',
            redirected: 'Передали',
            first_reaction: 'Первый ответ',
        },
        minutes: (n: number) => `${n} мин`,
    },
    request: {
        title: (id: number) => `Заявка № ${id}`,
        openRow: 'Открыть заявку',
        where: 'Где это',
        what: 'Что случилось',
        invalidTitle: 'Заявка',
        execution: 'Кто и когда сделает',
        showDetails: 'Показать',
        hideDetails: 'Скрыть',
        responsible: 'Кто отвечает',
        deadline: 'К какому сроку',
        replyDeadline: 'До какого дня ответить по закону',
        basis: 'Основание',
        unsure: 'Это пока неточно. Если нужно — передайте другой службе.',
        history: 'Что уже было',
        executor: 'Мастер',
        noExecutor: 'Мастера пока нет',
        assign: 'Назначить',
        assignEmpty: 'Сначала добавьте мастеров в организации.',
        assigned: 'Назначен',
        takeWork: 'В работу',
        takenWork: 'Заявка взята в работу',
        executorAssigned: 'Исполнитель назначен',
        workDone: 'Работа завершена',
        requestRedirected: 'Заявка передана',
        confirmedDone: 'Решение подтверждено',
        returnedToWork: 'Заявка возвращена в работу',
        finish: 'Завершить',
        commentTitle: 'Комментарий',
        commentPlaceholder: 'Напишите, что сделали или что мешает',
        commentAdded: 'Комментарий добавлен',
        templates: 'Шаблон ответа',
        templateOptions: ['Выехал', 'Ждём доступ в квартиру', 'Нужна запчасть', 'Передал мастеру'],
        actions: { redirect: 'Передать другой службе', comment: 'Написать комментарий' },
        notFound: 'Эту заявку не нашли. Нажмите Назад.',
        returnedBadge: 'Житель сказал: ещё не готово',
        joined: (n: number) => `Соседей с той же проблемой: ${n}`,
        neighbors: 'Соседи',
        redirected: 'Кому передали',
        photos: 'Фотографии',
        residentPhoto: 'Фото жителя',
        closingPhoto: 'Фото после работы',
        closingRound: (n: number) => `Фото после работы, ${n}-й раз`,
        photoComment: 'Комментарий',
        historyEmpty: 'Пока ничего не происходило',
        actionTitle: 'Что сделать',
        resolvedTitle: 'Проблему решили?',
        finishTitle: 'Работа закончена?',
        finishComment: 'Напишите, что сделали',
        addPhoto: 'Добавить фото',
        morePhotos: (n: number) => (n === 1 ? 'Ещё 1 фото' : `Ещё ${n} фото`),
        hidePhotos: 'Скрыть',
        selectedPhotos: (n: number) => `Фото: ${n} из 5`,
        removePhoto: (name: string) => `Убрать фото «${name}»`,
        photoLimit: 'Можно не больше пяти фото.',
        finishSubmit: 'Подтвердить',
        redirectName: 'Какой службе передать',
        redirectPhone: 'Телефон, если есть',
        redirectNote: 'Что сказать жителю',
        redirectSubmit: 'Передать заявку',
        returnComment: 'Напишите, что ещё не так',
        confirmYes: 'Да, всё хорошо',
        confirmNo: 'Нет, ещё не готово',
        events: {
            created: 'Заявка принята',
            assigned: 'Назначен исполнитель',
            statusChanged: 'Статус изменён',
            redirected: 'Заявка переадресована',
            returned: 'Житель вернул заявку в работу',
            confirmed: 'Решение подтверждено',
            comment: 'Комментарий',
            photoAdded: 'Добавлена фотография',
            participantJoined: 'Присоединился сосед',
            notification: 'Жителю отправлено уведомление',
            reminder: 'Отправлено напоминание',
        },
    },
    errors: {
        network: 'Нет связи. Проверьте интернет и повторите.',
        unauthorized: 'Сессия истекла. Откройте кабинет заново.',
        forbidden: 'Нет доступа к этому действию.',
        notFound: 'Такой заявки нет.',
        conflict: 'Заявка уже изменилась. Обновите страницу.',
        validation: 'Проверьте данные и попробуйте ещё раз.',
        server: 'Сервер не ответил. Попробуйте ещё раз.',
        later: 'Извините, повторите позже.',
        page: 'Страница сломалась. Обновите или вернитесь назад.',
        generic: 'Что-то пошло не так. Попробуйте ещё раз.',
    },
} as const;
