/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/max": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход из мини-приложения по initData MAX */
        post: operations["authMax"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход тестовой учётки (только DEMO_ACCOUNTS_ENABLED) */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отозвать текущий токен */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль, организация, дом */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дерево категорий со сроками и основаниями */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Очередь организации диспетчера */
        get: operations["listRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка заявки */
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Смена статуса по таблице переходов */
        patch: operations["changeStatus"];
        trace?: never;
    };
    "/requests/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Назначить исполнителя */
        post: operations["assignExecutor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Закрыть с фото — статус «Выполнено», запрос подтверждения у жителя */
        post: operations["closeRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/redirect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Переадресовать с контактом (терминальный статус) */
        post: operations["redirectRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Комментарий диспетчера в ленту без смены статуса */
        post: operations["addComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Житель подтверждает решение или возвращает заявку в работу */
        post: operations["confirmRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Заявки жителя */
        get: operations["myRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка организации диспетчера */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Контакты организации и флаги прямых договоров с РСО */
        patch: operations["updateOrganization"];
        trace?: never;
    };
    "/organization/houses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дома организации с QR-ссылкой и состоянием домового чата */
        get: operations["listHouses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/houses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Подъезды и подсказки по словам в домовом чате */
        patch: operations["updateHouse"];
        trace?: never;
    };
    "/organization/houses/{id}/qr.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PNG с QR-кодом deep link дома по подписанной ссылке qr_url из карточки дома */
        get: operations["houseQr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/executors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Действующие исполнители организации — список для назначения */
        get: operations["listExecutors"];
        put?: never;
        /** Добавить исполнителя */
        post: operations["createExecutor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/executors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Убрать исполнителя из списка; заявки, где он назначен, сохраняют историю */
        delete: operations["archiveExecutor"];
        options?: never;
        head?: never;
        /** Имя, телефон или специальность исполнителя */
        patch: operations["updateExecutor"];
        trace?: never;
    };
    "/organization/contractors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Подрядчики организации по договору (лифтовая, домофонная, ТКО) — перекрывают региональные стороны */
        get: operations["listContractors"];
        put?: never;
        /** Добавить подрядчика; новые заявки его типа пойдут ему */
        post: operations["createContractor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization/contractors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Убрать подрядчика; заявки хранят снимок ответственного и не меняются */
        delete: operations["deleteContractor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка организации для жителя — контакты и прямые договоры, без персональных данных */
        get: operations["getOrganizationCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Журнал заявок организации за период со сводкой */
        get: operations["journal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Журнал заявок за период в CSV по форме журнала АДС — разделитель «;», BOM для Excel */
        get: operations["journalCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal/csv-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Подписанная ссылка на CSV журнала за период на 10 минут; мини-приложение открывает её в браузере телефона, потому что само сохранить файл не может */
        get: operations["journalCsvLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CSV журнала по подписанной ссылке из /journal/csv-link, тот же файл, что /journal.csv */
        get: operations["journalCsvSigned"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Файл по подписанной ссылке (expires, signature в query) */
        get: operations["getAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сброс демо-данных (только сотрудник демо-организации) */
        post: operations["demoReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @example invalid_transition */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
                request_id?: string;
            };
        };
        /** @enum {string} */
        RequestStatus: "new" | "assigned" | "in_progress" | "done" | "confirmed" | "returned" | "redirected";
        /** @enum {string} */
        Role: "resident" | "dispatcher" | "admin";
        Organization: {
            id: number;
            name: string;
            /** @enum {string} */
            type: "uk" | "tsj" | "jsk";
            phone_ads: string;
            phone_dispatch?: string | null;
            email?: string | null;
            reception_hours?: string | null;
            reception_address?: string | null;
            direct_contracts: {
                cold_water: boolean;
                hot_water: boolean;
                heat: boolean;
                power: boolean;
                tko: boolean;
            };
            is_demo: boolean;
        };
        House: {
            id: number;
            address: string;
            entrances: number;
            qr_token: string;
            /** @description домовой чат привязан командой /дом <код> */
            chat_bound: boolean;
            /** @description карточка дома закреплена в чате; для этого бот должен быть администратором чата */
            chat_pinned: boolean;
            /** @description бот предлагает присоединиться к открытой заявке, когда в чате пишут о той же проблеме */
            chat_keywords_enabled: boolean;
            /** @description deep link дома для QR-плаката и кнопки в чате */
            start_url: string;
            /** @description подписанная ссылка на PNG с QR-кодом deep link дома, без срока действия; для плаката в подъезде добавьте &entrance=N */
            qr_url: string;
        };
        User: {
            id: number;
            name: string;
            role: components["schemas"]["Role"];
            organization?: components["schemas"]["Organization"] | null;
            house?: components["schemas"]["House"] | null;
            entrance?: number | null;
            flat?: string | null;
            is_demo: boolean;
        };
        AuthToken: {
            token: string;
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        Deadline: {
            value: number;
            /** @enum {string} */
            unit: "hours" | "days" | "working_days";
        };
        Category: {
            id: number;
            slug: string;
            name: string;
            is_emergency: boolean;
            responsible_type?: string | null;
            deadline_fix?: components["schemas"]["Deadline"] | null;
            deadline_reply?: components["schemas"]["Deadline"] | null;
            basis?: string | null;
            advice?: string | null;
            /** @description строка справочника помечена «сверить с первоисточником» */
            verify: boolean;
            children?: components["schemas"]["Category"][];
        };
        Executor: {
            id: number;
            name: string;
            specialty?: string | null;
            phone?: string | null;
        };
        /** @description Частичное обновление: передаются только меняемые поля */
        OrganizationUpdate: {
            name?: string;
            /** @description аварийная служба, обязательна */
            phone_ads?: string;
            phone_dispatch?: string | null;
            email?: string | null;
            reception_hours?: string | null;
            reception_address?: string | null;
            /** @description прямые договоры с РСО: при включённом флаге по коммунальной услуге отвечает поставщик */
            direct_contracts?: {
                cold_water?: boolean;
                hot_water?: boolean;
                heat?: boolean;
                power?: boolean;
                tko?: boolean;
            };
        };
        HouseUpdate: {
            entrances?: number;
            chat_keywords_enabled?: boolean;
        };
        ExecutorInput: {
            name: string;
            phone?: string | null;
            specialty?: string | null;
        };
        ExecutorUpdate: {
            name?: string;
            phone?: string | null;
            specialty?: string | null;
        };
        Contractor: {
            id: number;
            /** @enum {string} */
            type: "lift" | "intercom" | "tko" | "other";
            type_label: string;
            name: string;
            phone?: string | null;
        };
        ContractorInput: {
            /**
             * @description подрядчик этого типа перекрывает региональную сторону при расчёте ответственного
             * @enum {string}
             */
            type: "lift" | "intercom" | "tko" | "other";
            name: string;
            phone?: string | null;
        };
        OrganizationResponse: {
            data: components["schemas"]["Organization"];
        };
        HouseResponse: {
            data: components["schemas"]["House"];
        };
        HouseListResponse: {
            data: components["schemas"]["House"][];
        };
        ExecutorResponse: {
            data: components["schemas"]["Executor"];
        };
        ExecutorListResponse: {
            data: components["schemas"]["Executor"][];
        };
        ContractorResponse: {
            data: components["schemas"]["Contractor"];
        };
        ContractorListResponse: {
            data: components["schemas"]["Contractor"][];
        };
        OkResponse: {
            data: {
                ok: boolean;
            };
        };
        RequestListItem: {
            /** @description номер заявки */
            id: number;
            status: components["schemas"]["RequestStatus"];
            status_label: string;
            category: string;
            description: string;
            address: string;
            entrance?: number | null;
            flat?: string | null;
            responsible_name: string;
            is_sure: boolean;
            /** Format: date-time */
            deadline_fix_at?: string | null;
            /** Format: date-time */
            deadline_reply_at?: string | null;
            is_overdue: boolean;
            executor?: components["schemas"]["Executor"] | null;
            participants_count: number;
            /** Format: date-time */
            created_at: string;
        };
        RequestEvent: {
            id: number;
            /** @enum {string} */
            type: "created" | "assigned" | "status_changed" | "redirected" | "returned" | "confirmed" | "comment" | "photo_added" | "participant_joined" | "notification" | "reminder";
            from_status?: string | null;
            to_status?: string | null;
            /** @enum {string} */
            actor_role: "resident" | "dispatcher" | "system";
            actor_name?: string | null;
            comment?: string | null;
            payload?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        Attachment: {
            id: number;
            /** @enum {string} */
            kind: "resident" | "closing";
            mime: string;
            /** @description подписанная ссылка на 15 минут */
            url?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RequestCard: {
            id: number;
            status: components["schemas"]["RequestStatus"];
            status_label: string;
            allowed_transitions: components["schemas"]["RequestStatus"][];
            category: {
                id: number;
                name: string;
                slug: string;
            };
            description: string;
            house: components["schemas"]["House"];
            entrance?: number | null;
            flat?: string | null;
            responsible: {
                /** @enum {string} */
                kind: "organization" | "party" | "unknown";
                name: string;
                phone?: string | null;
                is_sure: boolean;
                party_id?: number | null;
            };
            /** Format: date-time */
            deadline_fix_at?: string | null;
            /** Format: date-time */
            deadline_reply_at?: string | null;
            basis: string;
            is_overdue: boolean;
            closed_late: boolean;
            executor?: components["schemas"]["Executor"] | null;
            /** Format: date-time */
            first_reaction_at?: string | null;
            /** Format: date-time */
            done_at?: string | null;
            /** Format: date-time */
            confirmed_at?: string | null;
            /** @enum {string|null} */
            confirmed_by?: "resident" | "auto" | "dispatcher" | null;
            /** Format: date-time */
            closed_at?: string | null;
            returned_count: number;
            redirected_to?: {
                party?: {
                    id: number;
                    name: string;
                    phone?: string | null;
                } | null;
                note?: string | null;
            };
            participants_count: number;
            /** @enum {string} */
            origin: "qr" | "chat" | "direct" | "api";
            rating?: number | null;
            events?: components["schemas"]["RequestEvent"][];
            attachments?: components["schemas"]["Attachment"][];
            /** Format: date-time */
            created_at: string;
        };
        Counters: {
            new: number;
            in_progress: number;
            overdue: number;
            closed: number;
        };
        PaginationMeta: {
            current_page: number;
            last_page: number;
            per_page: number;
            total: number;
            counters?: components["schemas"]["Counters"];
        };
        RequestCardResponse: {
            data: components["schemas"]["RequestCard"];
        };
        RequestListResponse: {
            data: components["schemas"]["RequestListItem"][];
            meta: components["schemas"]["PaginationMeta"];
            links?: {
                [key: string]: unknown;
            };
        };
        JournalRow: {
            /** @description номер заявки */
            id: number;
            /** Format: date-time */
            created_at: string;
            address: string;
            entrance?: number | null;
            flat?: string | null;
            /** @description после /delete_me — «Житель (удалён)» */
            resident_name: string;
            category: string;
            description: string;
            responsible_name: string;
            responsible_phone?: string | null;
            /** Format: date-time */
            deadline_fix_at?: string | null;
            basis: string;
            status: components["schemas"]["RequestStatus"];
            status_label: string;
            executor_name?: string | null;
            /** Format: date-time */
            first_reaction_at?: string | null;
            /** Format: date-time */
            done_at?: string | null;
            /** Format: date-time */
            closed_at?: string | null;
            is_overdue: boolean;
            /** @description выполнена после срока */
            closed_late: boolean;
            /** @enum {string|null} */
            confirmed_by?: "resident" | "auto" | "dispatcher" | null;
            returned_count: number;
            redirected_to?: string | null;
            participants_count: number;
        };
        JournalSummary: {
            /** @description заявок принято за период */
            total: number;
            open: number;
            /** @description открытые, у которых срок уже вышел */
            overdue: number;
            /** @description подтверждено или переадресовано */
            closed: number;
            /** @description выполнено до срока */
            on_time: number;
            /** @description выполнено после срока */
            late: number;
            /** @description заявок, которые житель хотя бы раз вернул */
            returned: number;
            redirected: number;
            /** @description среднее время до первого действия диспетчера; null, если действий не было */
            first_reaction_minutes: number | null;
        };
        JournalMeta: {
            current_page: number;
            last_page: number;
            per_page: number;
            total: number;
            period: {
                /** Format: date */
                from: string;
                /** Format: date */
                to: string;
            };
            summary: components["schemas"]["JournalSummary"];
        };
        JournalResponse: {
            data: components["schemas"]["JournalRow"][];
            meta: components["schemas"]["JournalMeta"];
            links?: {
                [key: string]: unknown;
            };
        };
        JournalCsvLink: {
            /** @description подписанная ссылка на CSV журнала за период; открывается без токена, например в браузере телефона */
            url: string;
            /**
             * Format: date-time
             * @description после этого времени ссылка отвечает 403
             */
            expires_at: string;
        };
    };
    responses: {
        /** @description Нет или просрочен токен */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не та роль или не та организация */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не найдено */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ошибка валидации; поля в details.fields */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Недопустимый переход статуса */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authMax: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description window.WebApp.initData как есть */
                    init_data: string;
                };
            };
        };
        responses: {
            /** @description Токен и профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthToken"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["Validation"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    login: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Токен и профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthToken"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готово */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            ok: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Корни с детьми */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Category"][];
                    };
                };
            };
        };
    };
    listRequests: {
        parameters: {
            query?: {
                /** @description группы: open — все незакрытые (new, assigned, in_progress, returned); active — в работе (assigned, in_progress, returned, done); closed — confirmed и redirected */
                status?: "open" | "active" | "closed" | "new" | "assigned" | "in_progress" | "done" | "confirmed" | "returned" | "redirected";
                overdue?: boolean;
                house_id?: number;
                q?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница очереди и счётчики вкладок */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["RequestStatus"];
                    comment?: string | null;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    assignExecutor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    executor_id: number;
                    comment?: string | null;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    closeRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    comment?: string;
                    photos?: string[];
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    redirectRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    responsible_party_id?: number | null;
                    name?: string | null;
                    phone?: string | null;
                    note?: string | null;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    addComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    confirmRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    resolved: boolean;
                    comment?: string | null;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    myRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Организация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    listHouses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Дома */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateHouse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HouseUpdate"];
            };
        };
        responses: {
            /** @description Обновлённый дом */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    houseQr: {
        parameters: {
            query: {
                signature: string;
                /** @description подъезд для плаката; в подпись не входит, добавляется к qr_url как есть */
                entrance?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Картинка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listExecutors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Исполнители по алфавиту */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutorListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createExecutor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutorInput"];
            };
        };
        responses: {
            /** @description Создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutorResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    archiveExecutor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готово */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateExecutor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutorUpdate"];
            };
        };
        responses: {
            /** @description Обновлённый исполнитель */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutorResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    listContractors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Подрядчики */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractorListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createContractor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractorInput"];
            };
        };
        responses: {
            /** @description Создан */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractorResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    deleteContractor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готово */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getOrganizationCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Организация */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    journal: {
        parameters: {
            query?: {
                /** @description дата приёма с, по зоне региона; по умолчанию первое число текущего месяца */
                from?: string;
                /** @description дата приёма по, включительно; по умолчанию сегодня; период не длиннее года */
                to?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Строки журнала по номеру заявки и сводка за период */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
        };
    };
    journalCsv: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
        };
    };
    journalCsvLink: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ссылка на файл */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["JournalCsvLink"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
        };
    };
    journalCsvSigned: {
        parameters: {
            query: {
                organization: number;
                from: string;
                to: string;
                expires: number;
                signature: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAttachment: {
        parameters: {
            query: {
                expires: number;
                signature: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    demoReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готово */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            ok: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
}
