/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/max": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход из мини-приложения по initData MAX */
        post: operations["authMax"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход тестовой учётки (только DEMO_ACCOUNTS_ENABLED) */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отозвать текущий токен */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Профиль, организация, дом */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Дерево категорий со сроками и основаниями */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Очередь организации диспетчера */
        get: operations["listRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка заявки */
        get: operations["getRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Смена статуса по таблице переходов */
        patch: operations["changeStatus"];
        trace?: never;
    };
    "/requests/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Назначить исполнителя */
        post: operations["assignExecutor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Закрыть с фото — статус «Выполнено», запрос подтверждения у жителя */
        post: operations["closeRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/redirect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Переадресовать с контактом (терминальный статус) */
        post: operations["redirectRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Комментарий диспетчера в ленту без смены статуса */
        post: operations["addComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Житель подтверждает решение или возвращает заявку в работу */
        post: operations["confirmRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/my/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Заявки жителя */
        get: operations["myRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Файл по подписанной ссылке (expires, signature в query) */
        get: operations["getAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сброс демо-данных (только сотрудник демо-организации) */
        post: operations["demoReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /** @example invalid_transition */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
                request_id?: string;
            };
        };
        /** @enum {string} */
        RequestStatus: "new" | "assigned" | "in_progress" | "done" | "confirmed" | "returned" | "redirected";
        /** @enum {string} */
        Role: "resident" | "dispatcher" | "admin";
        Organization: {
            id: number;
            name: string;
            /** @enum {string} */
            type: "uk" | "tsj" | "jsk";
            phone_ads: string;
            phone_dispatch?: string | null;
            email?: string | null;
            reception_hours?: string | null;
            reception_address?: string | null;
            direct_contracts: {
                cold_water: boolean;
                hot_water: boolean;
                heat: boolean;
                power: boolean;
                tko: boolean;
            };
            is_demo: boolean;
        };
        House: {
            id: number;
            address: string;
            entrances: number;
            qr_token: string;
            chat_bound: boolean;
        };
        User: {
            id: number;
            name: string;
            role: components["schemas"]["Role"];
            organization?: components["schemas"]["Organization"] | null;
            house?: components["schemas"]["House"] | null;
            entrance?: number | null;
            flat?: string | null;
            is_demo: boolean;
        };
        AuthToken: {
            token: string;
            /** Format: date-time */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        Deadline: {
            value: number;
            /** @enum {string} */
            unit: "hours" | "days" | "working_days";
        };
        Category: {
            id: number;
            slug: string;
            name: string;
            is_emergency: boolean;
            responsible_type?: string | null;
            deadline_fix?: components["schemas"]["Deadline"] | null;
            deadline_reply?: components["schemas"]["Deadline"] | null;
            basis?: string | null;
            advice?: string | null;
            /** @description строка справочника помечена «сверить с первоисточником» */
            verify: boolean;
            children?: components["schemas"]["Category"][];
        };
        Executor: {
            id: number;
            name: string;
            specialty?: string | null;
            phone?: string | null;
        };
        RequestListItem: {
            /** @description номер заявки */
            id: number;
            status: components["schemas"]["RequestStatus"];
            status_label: string;
            category: string;
            description: string;
            address: string;
            entrance?: number | null;
            flat?: string | null;
            responsible_name: string;
            is_sure: boolean;
            /** Format: date-time */
            deadline_fix_at?: string | null;
            /** Format: date-time */
            deadline_reply_at?: string | null;
            is_overdue: boolean;
            executor?: components["schemas"]["Executor"] | null;
            participants_count: number;
            /** Format: date-time */
            created_at: string;
        };
        RequestEvent: {
            id: number;
            /** @enum {string} */
            type: "created" | "assigned" | "status_changed" | "redirected" | "returned" | "confirmed" | "comment" | "photo_added" | "participant_joined" | "notification" | "reminder";
            from_status?: string | null;
            to_status?: string | null;
            /** @enum {string} */
            actor_role: "resident" | "dispatcher" | "system";
            actor_name?: string | null;
            comment?: string | null;
            payload?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        Attachment: {
            id: number;
            /** @enum {string} */
            kind: "resident" | "closing";
            mime: string;
            /** @description подписанная ссылка на 15 минут */
            url?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RequestCard: {
            id: number;
            status: components["schemas"]["RequestStatus"];
            status_label: string;
            allowed_transitions: components["schemas"]["RequestStatus"][];
            category: {
                id: number;
                name: string;
                slug: string;
            };
            description: string;
            house: components["schemas"]["House"];
            entrance?: number | null;
            flat?: string | null;
            responsible: {
                /** @enum {string} */
                kind: "organization" | "party" | "unknown";
                name: string;
                phone?: string | null;
                is_sure: boolean;
                party_id?: number | null;
            };
            /** Format: date-time */
            deadline_fix_at?: string | null;
            /** Format: date-time */
            deadline_reply_at?: string | null;
            basis: string;
            is_overdue: boolean;
            closed_late: boolean;
            executor?: components["schemas"]["Executor"] | null;
            /** Format: date-time */
            first_reaction_at?: string | null;
            /** Format: date-time */
            done_at?: string | null;
            /** Format: date-time */
            confirmed_at?: string | null;
            /** @enum {string|null} */
            confirmed_by?: "resident" | "auto" | "dispatcher" | null;
            /** Format: date-time */
            closed_at?: string | null;
            returned_count: number;
            redirected_to?: {
                party?: {
                    id: number;
                    name: string;
                    phone?: string | null;
                } | null;
                note?: string | null;
            };
            participants_count: number;
            /** @enum {string} */
            origin: "qr" | "chat" | "direct" | "api";
            rating?: number | null;
            events?: components["schemas"]["RequestEvent"][];
            attachments?: components["schemas"]["Attachment"][];
            /** Format: date-time */
            created_at: string;
        };
        Counters: {
            new: number;
            in_progress: number;
            overdue: number;
            closed: number;
        };
        PaginationMeta: {
            current_page: number;
            last_page: number;
            per_page: number;
            total: number;
            counters?: components["schemas"]["Counters"];
        };
        RequestCardResponse: {
            data: components["schemas"]["RequestCard"];
        };
        RequestListResponse: {
            data: components["schemas"]["RequestListItem"][];
            meta: components["schemas"]["PaginationMeta"];
            links?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Нет или просрочен токен */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не та роль или не та организация */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не найдено */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ошибка валидации; поля в details.fields */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Недопустимый переход статуса */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authMax: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description window.WebApp.initData как есть */
                    init_data: string;
                };
            };
        };
        responses: {
            /** @description Токен и профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthToken"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            422: components["responses"]["Validation"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    login: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Токен и профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AuthToken"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готово */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            ok: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Профиль */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Корни с детьми */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Category"][];
                    };
                };
            };
        };
    };
    listRequests: {
        parameters: {
            query?: {
                status?: "open" | "closed" | "new" | "assigned" | "in_progress" | "done" | "confirmed" | "returned" | "redirected";
                overdue?: boolean;
                house_id?: number;
                q?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница очереди и счётчики вкладок */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["Validation"];
        };
    };
    getRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    status: components["schemas"]["RequestStatus"];
                    comment?: string | null;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    assignExecutor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    executor_id: number;
                    comment?: string | null;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    closeRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    comment?: string;
                    photos?: string[];
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    redirectRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    responsible_party_id?: number | null;
                    name?: string | null;
                    phone?: string | null;
                    note?: string | null;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    addComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
        };
    };
    confirmRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    resolved: boolean;
                    comment?: string | null;
                };
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCardResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
        };
    };
    myRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestListResponse"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getAttachment: {
        parameters: {
            query: {
                expires: number;
                signature: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    demoReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готово */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            ok: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
}
